### ISSUE TITLE
How did you generate `example.gif`?

### ISSUE THREAD

**Issue by nicolasbock** [tianon/gosleep#3]
Hi,

I was wondering how you generated https://github.com/tianon/gosleep/blob/master/example.gif

Thanks!

**Comment by tianon** [comment]
I just used `byzanz` (https://github.com/GNOME/byzanz; I use XFCE as my WM, and actually ran it inside a container with a short shell script on the host to determine the exact coordinates I wanted it to record which worked well enough for what I needed).

**Comment by nicolasbock** [comment]
Thanks!
